### ISSUE TITLE
install fail file fonts/FontAwesome.otf exists in

### ISSUE THREAD

**Issue by adsl99801** [MyPureCloud/fixtable-ember#81] opened 2017-01-12 06:47 UTC
home@DESKTOP-6KJ8TSQ c:\keith\emberProject\data_managerment
$ ember build
cleaning up...
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (otherAssetTrees)] failed with:
Error: Merge error: file fonts/FontAwesome.otf exists in c:\keith\emberProject\data_managerment\tmp\broccoli_merge_trees-input_base_path-MIcXya4p.tmp\1 and c:\keith\emberProject\data_managerment\tmp\broccoli_merge_trees-input_base_path-MIcXya4p.tmp\2
Pass option { overwrite: true } to mergeTrees in order to have the latter file win.
    at BroccoliMergeTrees._mergeRelativePath (c:\keith\emberProject\data_managerment\node_modules\broccoli-merge-trees\index.js:274:17)
    at BroccoliMergeTrees._mergeRelativePath (c:\keith\emberProject\data_managerment\node_modules\broccoli-merge-trees\index.js:300:31)
    at BroccoliMergeTrees.build (c:\keith\emberProject\data_managerment\node_modules\broccoli-merge-trees\index.js:82:24)
    at c:\keith\emberProject\data_managerment\node_modules\broccoli-plugin\read_compat.js:61:34
    at tryCatch (c:\keith\emberProject\data_managerment\node_modules\rsvp\dist\rsvp.js:538:12)
    at invokeCallback (c:\keith\emberProject\data_managerment\node_modules\rsvp\dist\rsvp.js:553:13)
    at publish (c:\keith\emberProject\data_managerment\node_modules\rsvp\dist\rsvp.js:521:7)
    at flush (c:\keith\emberProject\data_managerment\node_modules\rsvp\dist\rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (c:\keith\emberProject\data_managerment\node_modules\broccoli-plugin\index.js:10:31)
    at new BroccoliMergeTrees (c:\keith\emberProject\data_managerment\node_modules\broccoli-merge-trees\index.js:42:10)
    at BroccoliMergeTrees (c:\keith\emberProject\data_managerment\node_modules\broccoli-merge-trees\index.js:36:53)
    at module.exports (c:\keith\emberProject\data_managerment\node_modules\ember-cli\lib\broccoli\merge-trees.js:8:14)
    at EmberApp.otherAssets (c:\keith\emberProject\data_managerment\node_modules\ember-cli\lib\broccoli\ember-app.js:1478:10)
    at EmberApp.toArray (c:\keith\emberProject\data_managerment\node_modules\ember-cli\lib\broccoli\ember-app.js:1648:10)
    at EmberApp.toTree (c:\keith\emberProject\data_managerment\node_modules\ember-cli\lib\broccoli\ember-app.js:1668:30)
    at module.exports (c:\keith\emberProject\data_managerment\ember-cli-build.js:71:14)
    at CoreObject.setupBroccoliBuilder (c:\keith\emberProject\data_managerment\node_modules\ember-cli\lib\models\builder.js:72:19)
    at CoreObject.init (c:\keith\emberProject\data_managerment\node_modules\ember-cli\lib\models\builder.js:52:10)

**Comment by menewman** [comment] 2017-01-12 07:34
Hi Keith,

Please provide some context beyond just the error message. Do you have a description of what you're trying to do and what the issue is? What are the steps to reproduce? What are your versions of node, npm, ember, and fixtable-ember?

**Comment by xdumaine** [comment] 2017-01-12 17:11
We just hit this as well. PR coming momentarily.

**Comment by menewman** [comment] 2017-01-12 17:33
@xdumaine This looks a lot like the issue that @toddjordan fixed in PRs #60 and #61. If you/your team are seeing this again, I'd love to have some additional context to poke into what's going on.

**Comment by menewman** [comment] 2017-01-20 18:32
Closing this due to lack of follow-up. Keith, please feel free to comment again if you still need help resolving this. It's probably an issue with your app having more than one addon that pulls in font-awesome, not something that's specifically an error with fixtable-ember.

**Closed by menewman** 2017-01-20 18:32 UTC
